 https://keras.io/guides/sequential_model/

## Setup

In [2]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

## When to use a Sequential model
A Sequential model is appropriate for a <b>plain stack of layers</b> where each layer has extactly <b>one input tensor and one output tensor </b>

In [13]:
# Define Sequential model with 3 layers
model=keras.Sequential([
    layers.Dense(2,activation='relu',name='layer1'),
    layers.Dense(3,activation='relu',name='layer2'),
    layers.Dense(4, name='layer3')
])

In [11]:
x=tf.ones((3,3))
print(x)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)


In [15]:
y=model(x)
print(y)

tf.Tensor(
[[-1.1195748  -0.06096781 -1.0454395  -0.34424478]
 [-1.1195748  -0.06096781 -1.0454395  -0.34424478]
 [-1.1195748  -0.06096781 -1.0454395  -0.34424478]], shape=(3, 4), dtype=float32)


In [17]:
model.layers

A Sequential model is not appropriate when

    - model has multiple inputs or multiple outputs
    - Any of layers has multiple inputs or multiple outputs
    - need to do layer sharing
    - want non-linear topology (e.g. residual connection, multi branch)