## Steup

In [1]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

In [2]:
# Create model using add() method
model=keras.Sequential()
model.add(layers.Dense(2,activation='relu'))
model.add(layers.Dense(3,activation='relu'))
model.add(layers.Dense(4))

In [3]:
model.layers

In [4]:
model.pop()
print(len(model.layers))

2


The Sequential constrctor accepts a name argument just like any layer or model in keras. this is useful to annotate Tensorboard graph with semantically


In [5]:
model=keras.Sequential(name='my_sequential')
model.add(layers.Dense(2,activation='relu',name='layer1'))
model.add(layers.Dense(3,activation='relu',name='layer2'))
model.add(layers.Dense(4,name='layer3'))

## Specifying the input shape in advance
Generally, all layers in keras need to know the shape of their input in order to be able to create their weights. so, when create a layer , it has no weights

In [9]:
layer=layers.Dense(3)
layer.weights

[]

it create its weights the first time it is called on a input, since the shape of the weights depends on the shape of the inputs

In [13]:
x=tf.ones((1,4))
print(x)
y=layer(x)
layer.weights 


tf.Tensor([[1. 1. 1. 1.]], shape=(1, 4), dtype=float32)


[<tf.Variable 'dense_4/kernel:0' shape=(4, 3) dtype=float32, numpy=
 array([[ 0.789698  ,  0.07939994, -0.34846765],
        [ 0.35108793, -0.03417492, -0.5141362 ],
        [-0.31228095,  0.08541298, -0.38449675],
        [-0.3399017 ,  0.18288767,  0.5511863 ]], dtype=float32)>,
 <tf.Variable 'dense_4/bias:0' shape=(3,) dtype=float32, numpy=array([0., 0., 0.], dtype=float32)>]

Naturally, this also applies to Sequential models. When you instantiate a Sequential model without an input shape, it isn't "built": it has no weights (and calling model.weights results in an error stating just this). The weights are created when the model first sees some input data

In [17]:
# model.summary() get error unless train the model
y=model(x)
print(y)

tf.Tensor([[-0.02364442 -0.02388514  0.07738669 -0.09752453]], shape=(1, 4), dtype=float32)


In [18]:
model.summary()

Model: "my_sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
layer1 (Dense)               (1, 2)                    10        
_________________________________________________________________
layer2 (Dense)               (1, 3)                    9         
_________________________________________________________________
layer3 (Dense)               (1, 4)                    16        
Total params: 35
Trainable params: 35
Non-trainable params: 0
_________________________________________________________________


However, it can be very useful when building a Sequential model incrementally to be able to display the summary of the model so far, including the current output shape. In this case, you should start your model by passing an Input object to your model, so that it knows its input shape from the start

In [20]:
model = keras.Sequential()
model.add(keras.Input(shape=(4,)))
model.add(layers.Dense(2, activation="relu"))

model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_6 (Dense)              (None, 2)                 10        
Total params: 10
Trainable params: 10
Non-trainable params: 0
_________________________________________________________________
